version: '3.8'

services:
  youtubio:
    build: .
    container_name: youtubio-addon
    ports:
      - "7000:7000"
    environment:
      - NODE_ENV=production
      - PORT=7000
    volumes:
      # Volume per persistere i dati dell'applicazione (cookies, configurazioni, ecc.)
      - ./data:/app/data
      # Volume per i logs (opzionale)
      - ./logs:/app/logs
    restart: unless-stopped
    networks:
      - youtubio-network

networks:
  youtubio-network:
    driver: bridge

volumes:
  youtubio-data:
    driver: local
